'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GenerateOrderingCodeForms.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #include	&lt;sys/types.h&gt;
        '''#include	&lt;sys/wait.h&gt;
        '''#include	&lt;errno.h&gt;		
        '''#include	&lt;stdarg.h&gt;
        '''#include	&quot;ourhdr.h&quot;
        '''
        '''char	*pname = NULL;		/* caller can set this from argv[0] */
        '''void pr_exit(int);
        '''static void err_doit(int, const char *, va_list);
        '''
        '''int main(void)
        '''{
        '''.
        '''</summary>
        Friend ReadOnly Property BeginCode() As String
            Get
                Return ResourceManager.GetString("BeginCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 	exit(0);
        '''}
        '''
        '''
        '''void pr_exit(int status)
        '''{
        '''	if (WIFEXITED(status))
        '''		printf(&quot;Exit status = %d\n&quot;,
        '''				WEXITSTATUS(status));
        '''	else if (WIFSIGNALED(status))
        '''		printf(&quot;abnormal termination, signal number = %d%s\n&quot;,
        '''				WTERMSIG(status),
        '''#ifdef	WCOREDUMP
        '''				WCOREDUMP(status) ? &quot; (core file generated)&quot; : &quot;&quot;);
        '''#else
        '''				&quot;&quot;);
        '''#endif
        '''	else if (WIFSTOPPED(status))
        '''		printf(&quot;child stopped, signal number = %d\n&quot;,
        '''				WSTOPSIG(status));
        '''}
        '''
        '''/* Fatal error related to a system call.
        ''' * Print a messag [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property EndCode() As String
            Get
                Return ResourceManager.GetString("EndCode", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
